[env:m5stack-sticks3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -DESP32S3
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DHAPTICS_ENABLE_AUDIO_BACKEND=0
  -DHAPTICS_ENABLE_REMOTE_BACKEND=0
  -DHAPTICS_ENABLE_TILT_SERVO=0
  -std=gnu++17
lib_deps =
  M5Unified=https://github.com/m5stack/M5Unified
  bblanchon/ArduinoJson@^6.21.5

[env:m5stack-sticks3-audio]
extends = env:m5stack-sticks3
build_unflags =
  -DHAPTICS_ENABLE_AUDIO_BACKEND=0
build_flags =
  ${env:m5stack-sticks3.build_flags}
  -DHAPTICS_ENABLE_AUDIO_BACKEND=1

[env:m5stack-sticks3-remote]
extends = env:m5stack-sticks3
build_unflags =
  -DHAPTICS_ENABLE_REMOTE_BACKEND=0
build_flags =
  ${env:m5stack-sticks3.build_flags}
  -DHAPTICS_ENABLE_REMOTE_BACKEND=1

[env:m5stack-sticks3-tilt]
extends = env:m5stack-sticks3
build_unflags =
  -DHAPTICS_ENABLE_TILT_SERVO=0
build_flags =
  ${env:m5stack-sticks3.build_flags}
  -DHAPTICS_ENABLE_TILT_SERVO=1
