using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace Fresnel.UnityDemo.Profiles
{
    public static class ProfileRegression
    {
        /// <summary>Cross-language corpus generated by the shipped Web codec; exports are consumed by verify-web-roundtrip.mjs.</summary>
        public static int Run()
        {
            string fixtures = Path.Combine(Application.dataPath, "Scripts", "Profiles", "Fixtures", "profile-corpus.json");
            var corpus = JObject.Parse(File.ReadAllText(fixtures));
            string output = Path.Combine(Application.temporaryCachePath, "FresnelProfileRoundtrip");
            Directory.CreateDirectory(output);
            int assertions = 0;
            foreach (JObject item in corpus["cases"])
            {
                string name = (string)item["name"], json = (string)item["json"];
                bool expected = (bool)item["valid"], accepted = false;
                TuningProfile profile = null;
                try { profile = ProfileCodec.Parse(json); accepted = true; } catch (FormatException) { }
                Check(accepted == expected, name + " acceptance differs from Web", ref assertions);
                if (!accepted) continue;
                string serialized = ProfileCodec.Serialize(profile);
                var roundtrip = ProfileCodec.Parse(serialized);
                Check(JToken.DeepEquals(JObject.Parse(ProfileCodec.Serialize(roundtrip)), JObject.Parse(serialized)), name + " serialization", ref assertions);
                File.WriteAllText(Path.Combine(output, name + ".json"), serialized);
            }
            foreach (string demo in new[] { "water", "marble", "sand" })
            {
                var baseline = ProfileCodec.ShippedBaselineValues(demo);
                var p = ProfileCodec.ShippedBaselineProfile(demo);
                Check(p.reviewStatus == "rehearsal-only" && p.comparisonCount == 0, "baseline invents evidence", ref assertions);
                foreach (string target in new[] { "water", "marble", "sand" })
                {
                    var targetValues = ProfileCodec.ShippedBaselineValues(target);
                    string second = target == "sand" ? "mass.granular_dynamic_friction" : "mass.damping_ratio_y";
                    targetValues[second] *= .9;
                    var transferred = ProfileCodec.ParametersFor(p, target, targetValues);
                    Check(transferred.Count == 7 && transferred[second] == (demo == target ? p.parameters[second] : targetValues[second]), "target material pair changed", ref assertions);
                }
                var detached = ProfileCodec.Validate(p); detached.parameters["tilt.k_phi"] = 2;
                Check(p.parameters["tilt.k_phi"] == 4, "validation retained mutable dictionary", ref assertions);
                p.parameters["tilt.k_phi"] = double.NaN;
                Reject(() => ProfileCodec.Validate(p), "NaN in public object", ref assertions);
            }
            string storeDirectory = Path.Combine(Application.temporaryCachePath, "FresnelProfileStoreRegression-" + Guid.NewGuid().ToString("N"));
            var store = new ProfileStore(storeDirectory);
            try
            {
                var a = ProfileCodec.ShippedBaselineProfile("marble");
                var b = ProfileCodec.ShippedBaselineProfile("water");
                store.SaveSlot("A", a); store.ImportSlot("B", ProfileCodec.Serialize(b));
                Check(store.LoadSlot("A").demo == "marble" && store.LoadSlot("B").demo == "water", "A/B storage", ref assertions);
                store.SaveSlot("A", b);
                Check(store.LoadSlot("A").demo == "water", "atomic replacement", ref assertions);
                Reject(() => store.LoadFile("../escape.json"), "filename traversal", ref assertions);
                Reject(() => store.SaveSlot("C", a), "invalid slot", ref assertions);
                Reject(() => store.ImportSlot("A", "{}"), "invalid import", ref assertions);
                Check(store.LoadSlot("A").demo == "water", "invalid import changed existing slot", ref assertions);
            }
            finally
            {
                // Only this test's fresh directory is touched; no user's saved selections are removed.
                foreach (string file in Directory.GetFiles(storeDirectory)) File.Delete(file);
                Directory.Delete(storeDirectory);
            }
            Debug.Log("FRESNEL_PROFILE_REGRESSION_OK " + assertions + " assertions; Web roundtrip directory: " + output);
            return assertions;
        }
        private static void Check(bool condition, string message, ref int count)
        { ++count; if (!condition) throw new InvalidOperationException("Profile regression failed: " + message); }
        private static void Reject(Action action, string label, ref int count)
        {
            bool rejected = false;
            try { action(); } catch (FormatException) { rejected = true; } catch (ArgumentException) { rejected = true; }
            Check(rejected, label, ref count);
        }
    }
}
