#pragma once

#ifndef HAPTICS_DEBUG_DISABLE_STORAGE
#define HAPTICS_DEBUG_DISABLE_STORAGE 0
#endif

#ifndef HAPTICS_DEBUG_FORCE_AUDIO_ON
#define HAPTICS_DEBUG_FORCE_AUDIO_ON 0
#endif

#ifndef HAPTICS_DEBUG_SYNTHETIC_STIMULUS
#define HAPTICS_DEBUG_SYNTHETIC_STIMULUS 0
#endif

#ifndef HAPTICS_DEBUG_DIRECT_TEXT_DISPLAY
#define HAPTICS_DEBUG_DIRECT_TEXT_DISPLAY 0
#endif
